# -*- coding: utf-8 -*-
"""
Esporta i dati STATICI delle bollette (gironi + selezioni + quote) verso la webapp.

Single source of truth: legge la sezione DATI di `genera_scommesse.py` ed esegue
SOLO le assegnazioni dei dati (F3/D3/G3/K2/bollette/GROUPS), senza toccare openpyxl
ne' generare l'xlsx. Cosi' la webapp e il foglio Excel non possono divergere.

Output: ../client/src/app/core/bets-data.ts  (GROUPS, BOLLETTE tipizzati)
Uso:    python src/genera_dati_web.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "genera_scommesse.py")
OUT = os.path.join(HERE, "..", "client", "src", "app", "core", "bets-data.ts")

src = open(SRC, encoding="utf-8").read()
# estrai solo il blocco dati: da "F3 = [" fino a (esclusa) "GROUP_ORDER"
start = src.index("F3 = [")
end = src.index("GROUP_ORDER")
ns = {}
exec(src[start:end], ns)  # definisce F3, D3, G3, K2, bollette, GROUPS  (nessuna dipendenza esterna)

bollette = ns["bollette"]
GROUPS = ns["GROUPS"]

groups_ts = [{"letter": g, "teams": list(teams)} for g, teams in GROUPS]
bollette_ts = []
for b in sorted(bollette):
    m = bollette[b]
    bollette_ts.append({
        "n": b,
        "stake": m["stake"],
        "ncomb": m["ncomb"],
        "imp": m["imp"],
        "vmin": m["vmin"],
        "vmax": m["vmax"],
        "sel": [{"grp": grp, "t1": p1, "t2": p2, "q": q} for (grp, p1, p2, q) in m["sel"]],
    })

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by src/genera_dati_web.py - do not edit by hand.\n")
    f.write("// Same data source as src/genera_scommesse.py (single source of truth).\n")
    f.write("import { Group, Bolletta } from './model';\n\n")
    f.write("export const GROUPS: Group[] = " + json.dumps(groups_ts, ensure_ascii=False) + ";\n\n")
    f.write("export const BOLLETTE: Bolletta[] = " + json.dumps(bollette_ts, ensure_ascii=False) + ";\n")

print("bets-data.ts generato:", len(groups_ts), "gironi,", len(bollette_ts), "bollette")
